//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_Wpf_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string CustomerCNIC { get; set; }
        public string CustomerContactNumber { get; set; }
        public string CustomerNTN { get; set; }
        public string CustomerSTRN { get; set; }
        public string OutletName { get; set; }
        public string OutletNumber { get; set; }
        public string CustomerAddress { get; set; }
    }
}
