//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_Wpf_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distribution
    {
        public int DistibutionId { get; set; }
        public string DistibutionName { get; set; }
        public string DistibutionAddress { get; set; }
        public string DistibutionNTN { get; set; }
        public string DistibutionSTRN { get; set; }
    }
}
