//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_Wpf_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesInfo
    {
        public int SalesOfficerId { get; set; }
        public string SalesOfficerName { get; set; }
        public string DeliveryManName { get; set; }
    }
}
