//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_Wpf_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class SKUTable
    {
        public int SKUId { get; set; }
        public string SKUCode { get; set; }
        public string SKUName { get; set; }
        public string TPRate { get; set; }
        public string SalesTax { get; set; }
        public string Promo { get; set; }
        public string NetRate { get; set; }
    }
}
